### ISSUE TITLE
Not 1, 2 but Yes/No selection for choices

### ISSUE THREAD

**Issue by teramonagi** [hoxo-m/githubinstall#5]
How about "Yes/No" selections to decide whether install or not like Linux based-OS do when the packages will be installed.

In addition to that, it might be good to set default setting "Yes".

### Example
- http://expresstaalk.blogspot.jp/2011/12/linux-network-install-ssh-in-ubuntu.html
![](http://www.basicconfig.com/files/imagepicker/j/jinlusuh/03_ssh.png)

**Comment by hoxo-m** [comment]
Sounds good! I'll try. Thank you.

**Comment by hoxo-m** [comment]
memo `update.packages()`

```
dplyr :
 Version 0.4.3 installed in /home/kmakiyam/R/x86_64-unknown-linux-gnu-library/3.1 
 Version 0.5.0 available at file://home/kmakiyam/miniCRAN
Update (y/N/c)?  
```

**Comment by hoxo-m** [comment]
Adopted version 0.1.0 has released. 
https://github.com/hoxo-m/githubinstall/releases/tag/v0.1.0
